myname: Racha Nagesh Kumar
message: Racha Nagesh Kumar!!!
server:
  port: 8089

# Service config  
apd-job-list:
  initializerGeneratedTestName: Initializer Generated Test

# Disable checking that the Config Service is available in the health check. Fail-fast is configured in bootstrap.yml so the
# application will not start if it's unable to get the configuration.
health:
  config:
    enabled: false

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
        exclude: shutdown
# Show health details
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      mielastic:
        step: 30000
        enabled: true

# Setup Eureka Registration Properties.
eureka:
  client:
    healthcheck:
      enabled: false
  instance:
    actuatorPrefix: ${management.endpoints.web.base-path}
    healthCheckUrlPath: ${eureka.instance.actuatorPrefix}/health
    statusPageUrlPath: ${eureka.instance.actuatorPrefix}/info
    metadataMap:
      management.context-path: ${eureka.instance.actuatorPrefix}
      smoketestPath: ${eureka.instance.actuatorPrefix}/smoketest
      health.path: ${eureka.instance.actuatorPrefix}/health

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-test-query: select 1 from dual
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 300000
      pool-name: job-list-connection-pool

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
